src/main/scala/org/broadinstitute/dsde/agora/server/ServerInitializer.scala
We were not sending this message from within an actor, and previously nobody was handling the response. This was resulting in dead letters in the case of success, and provided no handling in the case of failure.
=> Fixed the handling of the return message from IO HTTP bind

.coveralls.yml, .travis.yml, README.md
Added a travis file so that travis will build and run tests whenever someone pushes. Also added coveralls file for integration with coveralls code coverage service.
=> Integrate with travis and coveralls

.gitignore, build.sbt, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/AgoraDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntityModel.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/ToolMongoDbTest.scala
Basic data access layer added.
=> Added entity/metadata model as per our discussions today.

.travis.yml, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/AgoraDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntityModel.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/ToolMongoDbTest.scala
Bring up test mongodb (added wait to ensure mongo is up)
=> Added auto incrementing id.

.dockerignore, Dockerfile
Removed Dockerfile from dockerignore.
Changed names to agora from methodsrepo
=> Added unit test mongodb instance on build.

src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/MethodsDbTest.scala
Get rid of mongo specific test and use the factory instead.
=> use factory in tests

src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoDao.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Also, fixed ApiServiceSpec tests so they are capable of failing.
=> Make json returned from search more concise

src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsAddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Changed Post Request to return 201 (rather than 200) when successfully adding a method
Updated unit test to verify this.
Added a bit more testing of 200 codes being returned elsewhere.
=> Changed Post Request to return 201 (rather than 200) when successfully adding a method

build.sbt, src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraDirectives.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraOpenAMDirectives.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceActor.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/MethodsDbTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraOpenAMMockDirectives.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Added mock OpenAM so we can run unit tests without integration testing.
Pull owner out of the OpenAM ticket on creation.
=> Added cromwell and vault common from artifactory.

src/test/resources/agora.conf, src/test/resources/reference.conf
=> Fix build.

src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraDirectives.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraOpenAMDirectives.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraOpenAMMockDirectives.scala
It would be nice to push this down to vault common.
=> Added the ability to get user name instead of common name.

build.sbt, src/main/resources/reference.conf
Also I rearranged the dependencies so they are alphabetical... as the list grows it makes it easier find what you are looking for.
=> Added slf4j adapter to log akka messages.

src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceActor.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/QueryHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/util/ServiceMessages.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/validation/AgoraValidation.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/validation/AgoraValidationRejection.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraConfigurationsSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraMethodsSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/validation/AgoraValidationTest.scala
Fixed configurations in swaggah
Fixed urls being hardcoded to methods.
Added rejection tests for posting to the wrong endpoint.
Fixed up some swagger stuff.
=> Added type validation on endpoints.

src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoClient.scala
Reverts broadinstitute/agora#70
=> Revert "pull agora static string into config file"

README.md, src/main/scala/org/broadinstitute/dsde/agora/server/ServerInitializer.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/QueryHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/configurations/ConfigurationsService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/util/ServiceMessages.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraMethodsSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraReferencesSpec.scala
Changed queryByNamespaceNameSnapshotId to querySingle. 
I tried to minimize the amount of logic in the route itself. Personally, I think this is more readable, and we should refactor the other routes. Let me know what you think.
Also added some file level comments -- stuff I would have found helpful when I first dove into the codebase.
=> added an only payload endpoint for execution service

.gitignore, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/AuthorizationProvider.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/gcs/GcsApiJsonSupport.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/gcs/GcsAuthorizationProvider.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/gcs/RoleTranslator.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/GoogleAccessControls.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/QueryHandler.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/AgoraAuthorizationTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/authorization/TestAuthorizationProvider.scala
ACL write permissions should work would google. Lots of changes made here, so lets do a group code review tomorrow morning before pulling it in.
=> Bt google acl write

src/scripts/agora.py
Supports both methods and configs
Does push, get-by-reference, and list.
Passing in the Oauth token as a CL argument for now. Getting this fixed more generally is a story in our backlog.
No fancy logging or exceptions- simply prints info/errors to stdout
=> Added a CLI python script

build.sbt
If TEST_CONFIG is set in your environment it will be used when sbt runs its tests.
=> Added config file env variable.

src/scripts/agora.py
The agora URL was hard coded to agora-ci.broadinstitute.org. I've defaulted it to agora-prod.broadinstitute.org, since that is what the orchestration service is using. I've also made it overridable, so you can pass in whatever you want, with -u.
=> Make base url configurable for CLI

src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/permissions/PermissionNotFoundException.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/permissions/PermissionsClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/exceptions/AgoraException.scala, src/main/scala/org/broadinstitute/dsde/agora/server/exceptions/PermissionNotFoundException.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/PerRequest.scala
also moved permissionException to exceptions folder;
=> inform user when PUT permission is unsuccessful

src/main/resources/swagger/agora.yaml, src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/PermissionBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/permissions/AccessControl.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/permissions/PermissionsClient.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraUnitTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/permissions/EntityPermissionsClientSpec.scala
Support a ‘public’ user which can give permissions to all authenticated
users.
=> public permissions

build.sbt, src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/Agora.scala, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/EmbeddedMongo.scala
This is to update the mongodb configuration to allow setting up replicate servers.
=> Merge develop changes to staging

src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/Agora.scala, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/EmbeddedMongo.scala
=> Update master to staging
