.coveralls.yml, README.md, build.sbt, project/plugins.sbt
-Fixed travis badge in README.
-Updated scoverage and coveralls jars (only updated scoverage to 1.0.4 instead of 1.1.0 because 1.1.0 changed the way it looks for our source files and is breaking for obscure reasons)
-Removed some unused stuff in build.sbt (we don't need the key related stuff in there because we're not using travis pro and our coveralls key is in a travis environment variable, see https://github.com/scoverage/sbt-coveralls)
=> Fix travis badge and coveralls

src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/test/scala/org/broadinstitute/dsde/agora/server/ApiServiceSpec.scala
We created a separate data model for POST requests so users could not supply values for things we want to create ourselves (like ID).
We also don't want them able to OMIT things we require. Like name. Therefore removed Options from these fields.
=> Add Request elements should not be optional.

Dockerfile
To accomodate WDL parser, need to move from java7 to java8. There is no open-jdk java 8 package. Had to go Oracle.
=> Modified dockerfile to bump java 7 -> java 8

src/test/resources/TESTMARKDOWN.md, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Added a test for successful storage of markdown in documentation
To satisfy DSDEEPB-46. Acceptance Criteria:
```
* There exists a metadata field which can accept a large (10KB) markdown representing tool documentation.
* There exists a unit test that validates that a 10kb string of github markdown is recovered without getting garbled
```
The metadata field exists. Here I'm adding the test. I made a little md file containing various markdown features.
I am concatenating that until it would be >10kb stored, and sending that through the webservice.
I am doing this the full way through the service, not just as a db test, because I want to make sure serialization/deserialization and spray marshalling etc. do not garble the string.
Only changed total testing time from 5s -> 6s
Also added …
=> Bt documentation test

src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala
Spray-swagger moved from core swagger 1.2 - 1.3
Our params are not path params, but rather query params. They are also not required.
=> Swagger updates to fix search in swaggerui

src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Searches on owner, documentation, synopsis, and payload were failing. I changed the order of fields in AgoraSearch to match those in AgoraEntity and it is now working.
I also fixed the unit tests in ApiServiceSpec. They were erroneously passing because we had statements using === but not wrapped in assert(). So even if the === statements return false, the tests would pass.
Lastly, I added additional unit tests to verify search on owner, documentation, synopsis, and payload.
=> Fix search and unit tests

build.sbt, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupport.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/PerRequest.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsAddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsQueryHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/util/ServiceMessages.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/MethodsDbTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Removed salat for bson -> json and back. Just use JSON mongo util. Updated per request from Rawls. String to DateTime implicit conversion to make the search work on a standard AgoraEntity. Added AgoraApiJsonSupport back since we
are using spray json again.
We probably want to make sure everyone has their code merged back to master before we merge this guy.
=> Removed salat for bson -> json and back. Just use JSON mongo util.

src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/Agora.scala, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/ServerInitializer.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupport.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsAddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsQueryHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/util/ApiUtil.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
I also made changes to how we're handling configuration, to avoid having duplicate lines like the following in multiple classes:
lazy val port = appConfig.as[Option[Int]]("webservice.port").getOrElse(8000)
I moved lines like this into AgoraConfig itself so they happen in one central place.
Most of the changes here are due to this configuration refactoring.
=> Add URL for detailed method record to each search listing

src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsAddHandler.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusinessTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Fix url building when namespace, name, or id is missing (return empty string). Populate createDate when inserting a new method.
=> Fix url building when data is missing, fix createDate

src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupport.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraError.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsAddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsQueryHandler.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
We were returning 4xx error responses in plain text format, which broke the swagger UI and hid the actual error message.
(Details: The swagger UI sends an "accepts" header requiring responses to be in JSON. That's ok for success responses, which are in JSON. But for 404 errors, for example, we were attempting to return a plain text error message. Spray tries to be smart about this, so instead of returning the plain text 404 error message, it returns a 406 to indicate that the response format does not match the "accepts" header.)
=> Return 4xx errors in JSON format to fix swagger UI

src/main/scala/org/broadinstitute/dsde/agora/server/webservice/methods/MethodsService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/validation/AgoraValidation.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/validation/AgoraValidationTest.scala
So we can return a 400 instead of a 500 if invalid.
=> Validate include and exclude fields up in MethodsService

Dockerfile, build.sbt
Since we go through the business layer which creates its dao directly we don't have control over configuration of the mongodb.
=> Copy the application conf after test.

src/main/scala/org/broadinstitute/dsde/agora/server/acls/GcsRole.scala, src/main/scala/org/broadinstitute/dsde/agora/server/acls/RoleTranslator.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraPermissions.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/acls/RoleTranslatorTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/business/AgoraAccessControlTest.scala
We have two levels of permissions: those on a namespace, and those on a method.
We populate namespace permissions solely by looking at the corresponding gcs bucket role.
We populate method permissions solely by looking at the corresponding gcs object role.
There are 5 possible permissions on both namespaces and methods (Read, Write, Create, Redact, Manage). All 5 can be populated on namespaces. For methods, only Read and Manage will ever be populated as long as we're using gcs acls as our back end (because there is no WRITER permission on object acls).
The translator does not try to model the idea that namespace Read implies method Read. It's up to callers to know that a user should be allowed to read a method if they have Read on the namespace but not on the method. Similarly, Write will …
=> Create translator between Google ACLs and Agora permissions

src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/AuthorizationProvider.scala, src/main/scala/org/broadinstitute/dsde/agora/server/business/AuthorizedAgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/gcs/GcsAuthorizationProvider.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/QueryHandler.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/acls/AgoraAuthorizationTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusinessTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/authorization/TestAuthorizationProvider.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Also, move authorization checks up from the business layer to the add and query handlers. Benefits of this are:
-We don't have to pass an AuthorizationProvider all the way down to the business layer
-We don't have to throw an exception in the business layer when a user is not authorized to insert
=> Restrict inserts to users with create permission

build.sbt
We were getting errors when doing sbt assembly because the latest cromwell snapshot jar released 6/30 includes a logback.xml file, which causes problems because agora has its own logback.xml too.
=> Ignore cromwell's logback.xml to avoid sbt assembly error

src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala
Our embedded urls had port 8000 in them, which is not actually what we want when agora runs behind a proxy. When we run behind a proxy we usually want to leave the port blank in the embedded url.
I created a new config parameter called embeddedUrl.port so that this can be set independently of whatever port we tell agora to bind to. So, for example we can have:
webservice.port=8000
embeddedUrl.port=443
Or we can just not specify embeddedUrl.port, in which case the port will be blank in the embedded url.
We still need the option of specifying a port in embedded urls, because people may sometimes run locally without a proxy and still want to have valid embedded urls.
=> Fix embedded urls

src/main/scala/org/broadinstitute/dsde/agora/server/GoogleCredentialHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/gcs/GcsAuthorizationProvider.scala
Quick fix to make the GoogleCredential token refresh when it expires. Pipeline has been changed to a function so the token will be checked before every call to Google.
=> google credential token now refreshes when it expires (every hour)

src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupport.scala, src/test/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupportTest.scala
Agora was blowing up when requests were coming from a OpenAM test user with no email set. We may want to block such users, but we shouldn't do it by blowing up. This pull request adds a custom json format that can deal with the empty email field.
=> Fix unmarshalling when OpenAm user's email is empty

src/scripts/agora.py
Previously, trying to push a method with the CLI would open an editor, requiring the user to type in a synopsis for every push. Now you can optionally specify it as a parameter, which makes for less typing.
=> Let users specify synopsis as parameter to CLI

src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/Agora.scala, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/ServerInitializer.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/MockAuthorizationProvider.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceActor.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/routes/MockAgoraDirectives.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraIntegrationTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraUnitTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusinessTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/AgoraAuthorizationTest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/GcsAuthorizationSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraImportSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Load and validate environment (local, dev, ci, prod) from typesafe config
conditionally use embeddedMongo based on environment (only if local)
Refactored to move MockAuthorizationProvider (nee TestAuthorizationProvider) from test to src.
Select gcsAuthorizationProvider or mockAuthorizationProvider based on environment (i.e. local uses mock).
Passed environment to Agora object so that unitTest and integrationTest could use different environments for their configuration.
Pushed env-specific initialization down to ServerInitializer and ApiServiceActor.
=> Improvements to agora testing

src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AddHandler.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/util/DockerHubClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/util/DockerHubJsonSupport.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraIntegrationTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraIntegrationTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusinessIntegrationSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/dataaccess/acls/GcsAuthorizationSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraImportIntegrationSpec.scala
Validate that a docker image referenced in WDL payload validates (that it exists in docker hub).
Validate that if WDL contains a docker reference and it is properly formatted,
that the docker image exists.  Dealt with both 'official' and 'personal'
docker hub images and optional tags.  Added integration tests.
=> Validate that a docker image referenced in WDL payload validates

src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoClient.scala, src/main/scala/org/broadinstitute/dsde/agora/server/dataaccess/mongo/AgoraMongoDao.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupport.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraEntity.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraService.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/routes/RouteHelpers.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraUnitTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraConfigurationsSpec.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
When Agora gets a query for configurations, we need to return not only the configuration but also info about the associated method. This pull request implements that functionality.
Changes:
-When inserting a configuration, find the method reference in the payload and use it to populate the methodId metadata field in the configuration
-When returning configurations, use the methodId field to find the associated method and embed its details in the configuration json
=> Add reference from Configuration to Method

src/main/resources/swagger/agora.json, src/main/resources/swagger/agora.yaml, src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala, src/main/scala/org/broadinstitute/dsde/agora/server/exceptions/ValidationException.scala, src/main/scala/org/broadinstitute/dsde/agora/server/model/AgoraApiJsonSupport.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/PerRequest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraTestData.scala
Rawls changed the configuration payload field "methodStoreMethod" to "methodRepoMethod"
We check for the existence of this field during validation, and we were checking by the old name.
Added better failure descriptions to our require statements
=> Small bug fix to configuration validation

src/main/resources/reference.conf, src/main/scala/org/broadinstitute/dsde/agora/server/Agora.scala, src/main/scala/org/broadinstitute/dsde/agora/server/AgoraConfig.scala, src/main/scala/org/broadinstitute/dsde/agora/server/exceptions/AgoraException.scala, src/main/scala/org/broadinstitute/dsde/agora/server/webservice/PerRequest.scala, src/test/scala/org/broadinstitute/dsde/agora/server/AgoraUnitTestSuite.scala, src/test/scala/org/broadinstitute/dsde/agora/server/webservice/ApiServiceSpec.scala
Configurable with supervisor.logging which is true by default.
Also set whether or not to instrument Agora on application creation (could be in the config if we want to move it later)
=> Removed supervisor error logging for tests.
